# Generated by Django 5.1.4 on 2025-02-22 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DjangoTable",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("is_deleted", models.BooleanField()),
            ],
            options={
                "db_table": "table",
                "ordering": ("id",),
            },
        ),
    ]
